window.env = {
  VITE_GOOGLE_CLIENT_ID: '__VITE_GOOGLE_CLIENT_ID__',
  VITE_MAX_FREELANCE_BY_ID_REVIEWS: '__VITE_MAX_FREELANCE_BY_ID_REVIEWS__',
  VITE_SERVICE_FEES: '__VITE_SERVICE_FEES__',
  VITE_FILE_SERVER_HOST: '__VITE_FILE_SERVER_HOST__',
  VITE_WEBSOCKET_HOST: '__VITE_WEBSOCKET_HOST__',
  VITE_BACKEND_HOST: '__VITE_BACKEND_HOST__'
};

