services:
  db:
    image: postgres:16
    container_name: freelance-marketplace-db
    restart: always
    environment:
      POSTGRES_USER: freelance-marketplace-db
      POSTGRES_PASSWORD: freelance-marketplace-db
      POSTGRES_DB: freelance-marketplace-db
    ports:
      - "5431:5432"
    volumes:
      - ./database:/var/lib/postgresql/data

  file-server:
    restart: always
    build:
      context: ./file-server
    container_name: go-file-server
    ports:
      - "8030:8030"
    volumes:
      - ./file-server/storage/uploads:/app/storage/uploads
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: freelance-marketplace-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend-network
    command: ["redis-server", "--requirepass", "freelance-redis-db"]

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:

