services:
  db:
    image: postgres:latest
    container_name: freelance-marketplace-db
    restart: always
    environment:
      POSTGRES_USER: freelance-marketplace-db
      POSTGRES_PASSWORD: freelance-marketplace-db
      POSTGRES_DB: freelance-marketplace-db
    ports:
      - "5431:5432"
    volumes:
      - ../database:/var/lib/postgresql/data

  file-server:
    restart: always
    build:
      context: ../file-server
    container_name: freelance-marketplace-file-server
    ports:
      - "8030:8030"
    volumes:
      - ../file-server/uploads:/app/uploads
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    container_name: file-server-nginx
    ports:
      - "80:80"
    volumes:
      - ../file-server/nginx.conf:/etc/nginx/nginx.conf:ro  #
    depends_on:
      - file-server
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  db_data:

